import os
import sys
from src.providers.rootdata import RootDataClient
from src.providers.coingecko import CoinGeckoClient  # <--- 导入新模块
from src.senders.email_sender import send_email
from src.export_excel import save_to_excel
from src.summarize import generate_market_analysis

def main():
    print(">>> [1/4] 开始抓取数据...")
    
    # 1. 抓取 RootData
    rd_client = RootDataClient()
    fund = rd_client.fetch_fundraising()
    air = rd_client.fetch_airdrops()
    eco = rd_client.fetch_ecosystem()
    unl = rd_client.fetch_token_unlocks()
    
    # 2. 抓取 CoinGecko (新增)
    cg_client = CoinGeckoClient()
    markets = cg_client.fetch_market_data(limit=30) # 抓前30名
    
    print(f"    - 融资: {len(fund)} | 行情: {len(markets)} 个代币")

    print(">>> [2/4] 生成分析简报...")
    # 传入 markets 数据
    summary_html = generate_market_analysis(fund, air, unl, eco, markets)

    print(">>> [3/4] 生成 Excel 附件...")
    excel_path = save_to_excel({
        "0.市场行情": markets,  # <--- 放在第一个表
        "1.融资事件": fund,
        "2.潜在空投": air,
        "3.代币解锁": unl,
        "4.生态变化": eco
    })

    print(">>> [4/4] 发送邮件...")
    email_body = f"""
    <h2>Web3 每日投研简报</h2>
    <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #0366d6;">
        {summary_html}
    </div>
    <p style="margin-top: 20px;">📎 <b>详细行情与数据请查看附件 Excel 表格。</b></p>
    <hr>
    <small>Generated by GitHub Actions</small>
    """
    
    attachments = [excel_path] if excel_path else []
    
    try:
        send_email(
            subject=f"🚀 Web3 日报: BTC行情 & 融资{len(fund)}起",
            body=email_body,
            env=os.environ,
            attachments=attachments
        )
        print("✅ 任务成功完成！")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
