import os
import sys
from src.providers.rootdata import RootDataClient
from src.senders.email_sender import send_email
from src.export_excel import save_to_excel
from src.summarize import generate_market_analysis

def main():
    print(">>> [1/4] 开始抓取数据...")
    # 初始化客户端
    client = RootDataClient()
    
    # 抓取数据
    fund = client.fetch_fundraising()
    air = client.fetch_airdrops()
    eco = client.fetch_ecosystem()
    unl = client.fetch_token_unlocks()
    
    print(f"    - 融资: {len(fund)} | 空投: {len(air)} | 解锁: {len(unl)}")

    print(">>> [2/4] 生成分析简报...")
    # 调用规则引擎生成 HTML
    summary_html = generate_market_analysis(fund, air, unl, eco)

    print(">>> [3/4] 生成 Excel 附件...")
    excel_path = save_to_excel({
        "1.融资事件": fund,
        "2.潜在空投": air,
        "3.代币解锁": unl,
        "4.生态变化": eco
    })

    print(">>> [4/4] 发送邮件...")
    email_body = f"""
    <h2>Web3 每日投研简报</h2>
    <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #0366d6;">
        {summary_html}
    </div>
    <p style="margin-top: 20px;">📎 <b>详细数据请查看附件 Excel 表格。</b></p>
    <hr>
    <small>Generated by GitHub Actions</small>
    """
    
    attachments = [excel_path] if excel_path else []
    
    try:
        send_email(
            subject=f"🚀 Web3 日报: 融资{len(fund)}起 | 空投{len(air)}个",
            body=email_body,
            env=os.environ,
            attachments=attachments
        )
        print("✅ 任务成功完成！")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
