import os
import sys
from src.providers.rootdata import RootDataClient
from src.providers.coingecko import CoinGeckoClient
from src.providers.cryptopanic import CryptoPanicClient # <--- 导入新模块
from src.senders.email_sender import send_email
from src.export_excel import save_to_excel
from src.summarize import generate_market_analysis

def main():
    print(">>> [1/5] 启动抓取任务...")
    
    # 1. RootData
    rd = RootDataClient()
    fund = rd.fetch_fundraising()
    air = rd.fetch_airdrops()
    eco = rd.fetch_ecosystem()
    unl = rd.fetch_token_unlocks()
    
    # 2. CoinGecko
    cg = CoinGeckoClient()
    markets = cg.fetch_market_data(limit=30)
    
    # 3. CryptoPanic (新增)
    # 从环境变量获取 Key
    cp_key = os.getenv("CRYPTOPANIC_API_KEY", "")
    cp = CryptoPanicClient(api_key=cp_key)
    news = cp.fetch_hot_news(limit=20)
    
    print(f"    - 融资:{len(fund)} | 行情:{len(markets)} | 新闻:{len(news)}")

    print(">>> [2/5] 生成分析简报...")
    # 传入 news 数据
    summary_html = generate_market_analysis(fund, air, unl, eco, markets, news)

    print(">>> [3/5] 生成 Excel 附件...")
    excel_path = save_to_excel({
        "0.市场行情": markets,
        "1.舆情热点": news,  # <--- 新增 Sheet
        "2.融资事件": fund,
        "3.潜在空投": air,
        "4.代币解锁": unl,
        "5.生态变化": eco
    })

    print(">>> [4/5] 发送邮件...")
    email_body = f"""
    <h2>Web3 每日投研简报</h2>
    <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #0366d6;">
        {summary_html}
    </div>
    <p style="margin-top: 20px;">📎 <b>详细数据请查看附件 Excel 表格。</b></p>
    <hr>
    <small>Generated by GitHub Actions</small>
    """
    
    attachments = [excel_path] if excel_path else []
    
    try:
        send_email(
            subject=f"🚀 Web3 日报: {len(news)}条热点 | 融资{len(fund)}起",
            body=email_body,
            env=os.environ,
            attachments=attachments
        )
        print("✅ 任务成功完成！")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()